language: ruby
rvm:
  - 1.9.3-p551
  - 2.0.0-p598
  - 2.1.5
cache:
  directories:
  - vendor/bundle
before_install:
  - sudo apt-get install -y libmp3lame0
  - pushd .
  - cd /usr/lib/x86_64-linux-gnu && sudo ln -s libmp3lame.so.0.0.0 libmp3lame.so
  - popd
script:
  - CODECLIMATE_REPO_TOKEN=5820e7c35ae826605f6ac87c88a1cb4e8b8d26f999a81abfbbabf31d0d0a6ff1 bundle exec rspec
